### ISSUE TITLE
Build issues with latest Trilinos (April 4, 2021)

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#843]
Multiple issues with: trilinos/trilinos#8597 

- Breaking header change addressed in f855815
- Build error tracked in trilinos/trilinos#8967

```
In file included from /home/sanantha/exawind/source/nalu-wind/src/Realm.C:158:
/nopt/nrel/ecom/exawind/exawind-2020-09-21/install/gcc/trilinos-2021-04-04/include/Iovs_exodus_DatabaseIO.h:18:10: fatal error: visualization/utils/Iovs_Utils.h: No such file or directory
 #include <visualization/utils/Iovs_Utils.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
